name: nodeip-configuration.service
enabled: {{if gt (len (onPremPlatformAPIServerInternalIPs .)) 0}}true{{else}}false{{end}}
contents: |
  [Unit]
  Description=Writes IP address configuration so that kubelet and crio services select a valid node IP
  # This only applies to VIP managing environments where the kubelet and crio IP
  # address picking logic is flawed and may end up selecting an address from a
  # different subnet or a deprecated address
  Wants=NetworkManager-wait-online.service crio-wipe.service
  After=NetworkManager-wait-online.service ignition-firstboot-complete.service crio-wipe.service
  Before=kubelet.service crio.service ovs-configuration.service

  [Service]
  # Need oneshot to delay kubelet
  Type=oneshot
  # Would prefer to do Restart=on-failure instead of this bash retry loop, but
  # the version of systemd we have right now doesn't support it. It should be
  # available in systemd v244 and higher.
  ExecStart=/bin/bash -c " \
    until \
    /usr/bin/podman run --rm \
    --authfile /var/lib/kubelet/config.json \
    --net=host \
    --security-opt label=disable \
    --volume /etc/systemd/system:/etc/systemd/system \
    --volume /run/nodeip-configuration:/run/nodeip-configuration \
    {{ .Images.baremetalRuntimeCfgImage }} \
    node-ip \
    set --retry-on-failure \
    {{ range onPremPlatformAPIServerInternalIPs . }}{{.}} {{end}}; \
    do \
    sleep 5; \
    done"
  ExecStart=/bin/systemctl daemon-reload
  ExecStartPre=/bin/mkdir -p /run/nodeip-configuration
  {{if .Proxy -}}
  EnvironmentFile=/etc/mco/proxy.env
  {{end -}}
  # Allow 5 minutes for this service to startup. This should be ample time to
  # determine if we're going to work, or if we need to fail and address problems.
  TimeoutSec=300

  [Install]
  WantedBy=multi-user.target
